#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8005
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 175.178.69.88:2181   # 此处的地址为腾讯云服务器地址