server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8011          #匹配后提供服务的路由地址，生产环境不建议使用写死的IP地址
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2021-11-09T14:20:33.532+08:00[Asia/Shanghai]  # 在该时间之后才能访问
            # - Before=2022-11-09T14:20:33.532+08:00[Asia/Shanghai]  # 断言，在该时间之前才能访问
            # Between=2022-02-02T17:45:06.206+08:00[Asia/Shanghai],2023-03-25T18:59:06.206+08:00[Asia/Shanghai] #在该时间间隔以内

            # - Cookie=username,123 #请求需要携带cookie，且cookie中有一参数名为username，值为123
            # curl http://localhost:9527/payment/get --cookie "username=123"

            # - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            # curl http://localhost:9527/payment/get -H "X-Request-Id:123"

            # - Host=**.atguigu.com  #请求中需要携带一级域名=com  二级域名atguigu 才能访问
            # curl http://localhost:9527/payment/get -H "Host: www.atguigu.com"

            # - Method=GET  # 只能接受GET请求
            # curl http://localhost:9527/payment/get

            # - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
            # curl http://localhost:9527/payment/get?username=31
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8011          #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka